name: Test and Lint

on:
  push:
    branches:
      - master
  pull_request:

env:
  NODE_VERSION: v16.15.1

jobs:
  test-and-lint:
    name: Test and Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: yarn
      - name: Install dependencies
        run: yarn install --immutable
      - name: Check files are formatted with Prettier
        run: yarn prettier --check './**/src/**/*.{js,jsx,ts,tsx,css,html,md}'
